# Generated by Django 3.1 on 2020-09-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=255)),
                ('finish_date', models.DateField()),
                ('priority', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tickets',
                'managed': False,
            },
        ),
    ]
